# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e820d9db2f6f52f161c35f2ce8f6767b0e6a84ad3ddb2e8158b6d4635ad108a181f5aa0052a2ef959feef437ee2d29be6e12768b4242326e38e4a1177a43ebb

test:
  secret_key_base: c2681555d050d2424929947eb12f7fd5c6e42610a40c0c8d94ef82275db22bfc5c505a491cf023b27abe0498ff2448fdd533e3f9fcf4a66b2e7c577a9ee2a965

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
